def patternCount(text, pattern):
    count = 0
    for i in range(0, len(text)-len(pattern)):
        if text[i:i+len(pattern)] == pattern:
            count += 1
    return count

def frequentWords(text, k):
    frequentPatterns = []
    counts = []
    for i in range(0, len(text)-k):
        pattern = text[i:i+k]
        count = patternCount(text, pattern)
        counts.append(count)
    maxCount = max(counts)
    for i in range(0, len(text)-k):
        if counts[i] == maxCount:
            frequentPatterns.append(text[i:i+k])
    frequentPatterns = list(set(frequentPatterns))
    return frequentPatterns

#print(frequentWords('GGTAAAATATACCAACGCATCCTACACGATCCTACACGATACCAACGCTTCGACAAGGTAAAATTTTCCCGCGGTAAAATATACCAACGCGGTAAAATTTCGACAATTTCCCGCATCCTACACGTTCGACAATTCGACAAGGTAAAATATACCAACGCGGTAAAATGGTAAAATTTTCCCGCGGTAAAATTTTCCCGCGGTAAAATGGTAAAATTTCGACAAGGTAAAATTTTCCCGCATACCAACGCTTCGACAAATCCTACACGTTTCCCGCTTCGACAAGGTAAAATTTTCCCGCATACCAACGCTTCGACAATTCGACAAATCCTACACGTTCGACAAGGTAAAATATCCTACACGTTTCCCGCTTTCCCGCTTTCCCGCATCCTACACGGGTAAAATGGTAAAATATACCAACGCATCCTACACGTTTCCCGCATACCAACGCTTCGACAAGGTAAAATATCCTACACGTTTCCCGCTTTCCCGCGGTAAAATATCCTACACGGGTAAAATGGTAAAATATCCTACACGTTCGACAAATACCAACGCTTTCCCGCATACCAACGCTTCGACAATTTCCCGCGGTAAAATTTCGACAAGGTAAAATGGTAAAATATACCAACGCATACCAACGCTTTCCCGCTTCGACAAATACCAACGCGGTAAAATGGTAAAATTTCGACAAATCCTACACGTTTCCCGCTTTCCCGCTTTCCCGCTTCGACAAATACCAACGCATCCTACACGTTTCCCGCGGTAAAATTTTCCCGCATACCAACGCTTCGACAAATCCTACACGGGTAAAATTTTCCCGCATCCTACACGTTTCCCGCTTTCCCGCTTTCCCGCATCCTACACGTTCGACAATTTCCCGCGGTAAAATGGTAAAATATACCAACGCATCCTACACGGGTAAAATATACCAACGCATACCAACGC', 14))
    